
  - name: Install apt-transport-http
    apt: name=apt-transport-https state=present update_cache=yes

  - name: Add packages.cloud.google.com repostitory key
    apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present

  - name: Add kubernetes apt repository
    apt_repository: repo='deb https://apt.kubernetes.io/ kubernetes-xenial main' state=present

  - name: Add gcloud apt repository
    shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

  - name: Add gcloud key ring
    shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

  - name: Install kubernetes
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - kubectl

  - name: Install gcloud
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - google-cloud-sdk
