- name: Install apt-transport-http
  apt: name=apt-transport-https state=installed update_cache=yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - docker-ce
    - containerd.io
    - docker-ce-cli

- name: Install Docker Module for Python
  pip:
  name: docker

- name: Pull default Docker image
  docker_image:
    name: "shieldsio/shields:next"
    source: pull
