- name: Install apt-transport-http
  apt: name=apt-transport-https state=installed update_cache=yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install containerd.io
  apt: update_cache=yes name=containerd.io state=latest

- name: Update apt and install docker-ce-cli
  apt: update_cache=yes name=docker-ce-cli state=latest

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
  name: docker

- name: Pull default Docker image
  docker_image:
    name: "shieldsio/shields:next"
    source: pull
