---

user_name: maykin
group_name: staff
project_name: vng
target: production
project_root: "/srv/sites/{{ project_name }}-{{ target }}"
project_src_dir: "vng"
celery_worker_path: "vng"
django_settings_module: "{{ project_src_dir }}.conf.{{ target }}"

pub_key_users:
  - alex
  - joeri
  - alvise

project_repo: git@github.com:VNG-Realisatie/api-testvoorziening-code.git
branch: master

nginx_server_name: "api-test.nl"
nginx_access_log_file: "{{ project_root }}/log/nginx/access.log"
nginx_error_log_file: "{{ project_root }}/log/nginx/error.log"
nginx_static_dir: "{{ project_root }}/static/"
nginx_media_dir: "{{ project_root }}/media/"

dbname: vngatvprod
dbuser: vngatv
# dbpassword: (see vault)

uwsgi_port: 8084


