---

user_name: maykin
group_name: staff
project_name: vng
target: staging
project_root: "/srv/sites/{{ project_name }}-{{ target }}"
project_src_dir: "vng"
celery_worker_path: "vng"
django_settings_module: "{{ project_src_dir }}.conf.{{ target }}"

pub_key_users:
  - alex
  - joeri
  - alvise

project_repo: git@github.com:VNG-Realisatie/api-testvoorziening-code.git
branch: develop

nginx_server_name: "{{ project_name }}-{{ target }}.maykin.nl"
nginx_access_log_file: "{{ project_root }}/log/nginx/access.log"
nginx_error_log_file: "{{ project_root }}/log/nginx/error.log"
nginx_static_dir: "{{ project_root }}/static/"
nginx_media_dir: "{{ project_root }}/media/"

nginx_basicauth_user: maykin
nginx_basicauth_password: nogniet

dbname: vng-staging
dbuser: vng-staging
dbpassword: vng-staging

uwsgi_port: 8105

new_relic_license_key: df267b81c76433faafdbc414918535ea9b22b425
